### ISSUE TITLE
Error with running standalone loss.py on PyTorch 1.7

### ISSUE THREAD

**Issue by listener17** [yanggeng1995/FB-MelGAN#6]
If I just run standalone loss.py as:
CUDA_VISIBLE_DEVICES=1 python loss.py   

I get the following error with PyTorch 1.7:

```

/home/listener17/anaconda3/envs/pytorch37/lib/python3.7/site-packages/torch/functional.py:516: UserWarning: stft will require the return_complex parameter be explicitly  specified in a future PyTorch release. Use return_complex=False  to preserve the current behavior or return_complex=True to return  a complex output. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370128159/work/aten/src/ATen/native/SpectralOps.cpp:653.)
  normalized, onesided, return_complex)
Traceback (most recent call last):
  File "loss.py", line 106, in <module>
    sc_loss, mag_loss = model(x, y)
  File "/home/listener17/anaconda3/envs/pytorch37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "loss.py", line 92, in forward
    sc_loss, mag_loss = layer(fake_signals.to(device="cuda"), true_signals.to(device="cuda"))
  File "/home/listener17/anaconda3/envs/pytorch37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "loss.py", line 69, in forward
    predicts_mag = stft(predicts, self.fft_size, self.hop_size, self.win_size, self.window)
  File "loss.py", line 15, in stft
    x_stft = torch.stft(x, fft_size, hop_size, win_size, window)
  File "/home/listener17/anaconda3/envs/pytorch37/lib/python3.7/site-packages/torch/functional.py", line 516, in stft
    normalized, onesided, return_complex)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by listener17** [comment]
Solved
